# Numpy
The nampay library is a library for working with matrix data, which generally have a large volume, and their calculations are based on linear algebra.

In [1]:
import numpy

In [2]:
vector = [1, 2, 3]

In [3]:
print(type(vector))

<class 'list'>


In [4]:
nvector = numpy.array(vector)

In [5]:
nvector.shape

(3,)

In [6]:
matrix = [
[1,2,3],
[4,5,6],
[7,8,9]
]

In [7]:
print(type(matrix))

<class 'list'>


In [8]:
matrix = numpy.array(matrix)

In [9]:
matrix.shape

(3, 3)

In [10]:
tensor = [
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
]

In [11]:
print(type(tensor))

<class 'list'>


In [12]:
tensor = numpy.array(tensor)

In [13]:
tensor.shape

(3, 3, 3)

In [14]:
narr = numpy.array([1, 2, 3])

In [15]:
numpy.resize(narr, (4,4))

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [16]:
narr.resize((3,3))
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [17]:
narr.resize((3,3), refcheck=False)
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [18]:
matrix = numpy.ones((5, 4))

In [19]:
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [20]:
matrix = numpy.zeros((5, 4))

In [21]:
numpy.diag(narr)

array([1, 0, 0])

In [22]:
numpy.repeat([4, 3, 2], 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [23]:
m1 = numpy.ones((5, 4), int)

In [24]:
m2 = numpy.zeros((5, 4), int)

In [25]:
numpy.vstack([m2, m1])

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [26]:
numpy.hstack([m1, m2])

array([[1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0]])

In [27]:
[1, 2, 3] * [4, 5, 6]

TypeError: can't multiply sequence by non-int of type 'list'

In [29]:
x = numpy.array([1, 2, 3])
y = numpy.array([4, 5, 6])

In [32]:
z=  x * y
z

array([ 4, 10, 18])

In [33]:
x ** 2

array([1, 4, 9])

In [34]:
x.dot(y)

32

In [35]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [36]:
m = narr.T
m

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [37]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [38]:
narr.sum()

6

In [39]:
narr.max()

3

In [40]:
narr.min()

0

In [41]:
narr.argmax()

2

In [42]:
narr.argmin()

3

In [43]:
narr.mean()

0.6666666666666666

In [44]:
narr.std()

1.0540925533894598

In [45]:
mr = numpy.arange(15) ** 2
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [46]:
mr[2]

4

In [47]:
mr[:5]

array([ 0,  1,  4,  9, 16])

In [48]:
mr[-2:]

array([169, 196])

In [49]:
mr[5:12:3]

array([ 25,  64, 121])

In [50]:
mr[-10::-2]

array([25,  9,  1])

In [51]:
mr[5:-1:-1]

array([], dtype=int32)

In [52]:
mr[5::-1]

array([25, 16,  9,  4,  1,  0])

In [53]:
mr[7::-1]

array([49, 36, 25, 16,  9,  4,  1,  0])

In [54]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [ ]:
narr = numpy.array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [57]:
narr[-2::1, 1:3]

array([[0, 0],
       [0, 0]])

In [59]:
narr[narr >= 2]

array([2, 3])

In [60]:
narr >= 2

array([[False,  True,  True],
       [False, False, False],
       [False, False, False]])

In [62]:
marr = narr[-1]
marr

array([0, 0, 0])

In [65]:
marr[:2] = 2
marr

array([2, 2, 0])

In [66]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 0]])

In [69]:
marr = narr[-1].copy()
marr

array([2, 2, 0])

In [70]:
marr[:2] = 3
marr

array([3, 3, 0])

In [71]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [2, 2, 0]])

In [73]:
tarr = numpy.random.randint(0, 10, (4, 3))
tarr

array([[4, 6, 9],
       [7, 6, 5],
       [9, 9, 1],
       [9, 7, 8]])

In [74]:
tarr[3::3, 4:1:-2]

array([[8]])

In [76]:
for r in tarr:
    r = r **2
    print(r)

[16 36 81]
[49 36 25]
[81 81  1]
[81 49 64]


In [77]:
for i, r in enumerate(tarr):
    print('index(' + str(i) + ') is ', r)

index(0) is  [4 6 9]
index(1) is  [7 6 5]
index(2) is  [9 9 1]
index(3) is  [9 7 8]


In [78]:
list(zip(narr, tarr))

[(array([1, 2, 3]), array([4, 6, 9])),
 (array([0, 0, 0]), array([7, 6, 5])),
 (array([2, 2, 0]), array([9, 9, 1]))]

In [80]:
arr = [1, 4, 2, 9, 8, 6, 3]
arr = numpy.array(arr)
arr

array([1, 4, 2, 9, 8, 6, 3])

In [81]:
def quicksort(arr):
    if len(arr) <= 1:
        return arr
    arr = numpy.array(arr)
    p = arr[len(arr) // 2]
    l = [x for x in arr if x < p]
    m = [x for x in arr if x == p]
    r = [x for x in arr if x > p]
    return quicksort(l) + m + quicksort(r)

In [83]:
h = [1, 4, 2, 9, 8, 6, 3]
quicksort(h)

[1, 2, 3, 4, 6, 8, 9]