# Numpy
The nampay library is a library for working with matrix data, which generally have a large volume, and their calculations are based on linear algebra.

In [1]:
import numpy

In [2]:
vector = [1, 2, 3]

In [3]:
print(type(vector))

<class 'list'>


In [4]:
nvector = numpy.array(vector)

In [5]:
nvector.shape

(3,)

In [14]:
matrix = [
[1,2,3],
[4,5,6],
[7,8,9]
]

In [15]:
print(type(matrix))

<class 'list'>


In [16]:
matrix = numpy.array(matrix)

In [17]:
matrix.shape

(3, 3)

In [18]:
tensor = [
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
    [[1, 2, 3], [4, 5, 6], [7, 8, 9]],
]

In [19]:
print(type(tensor))

<class 'numpy.ndarray'>


In [21]:
tensor = numpy.array(tensor)

In [22]:
tensor.shape

(3, 3, 3)

In [54]:
narr = numpy.array([1, 2, 3])

In [55]:
numpy.resize(narr, (4,4))

array([[1, 2, 3, 1],
       [2, 3, 1, 2],
       [3, 1, 2, 3],
       [1, 2, 3, 1]])

In [53]:
narr.resize((3,3))
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [56]:
narr.resize((3,3), refcheck=False)
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [30]:
matrix = numpy.ones((5, 4))

In [31]:
matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [32]:
matrix = numpy.zeros((5, 4))

In [35]:
numpy.diag(narr)

array([1, 0, 0])

In [36]:
numpy.repeat([4, 3, 2], 5)

array([4, 4, 4, 4, 4, 3, 3, 3, 3, 3, 2, 2, 2, 2, 2])

In [38]:
m1 = numpy.ones((5, 4), int)

In [37]:
m2 = numpy.zeros((5, 4), int)

In [39]:
numpy.vstack([m2, m1])

array([[0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [0, 0, 0, 0],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1],
       [1, 1, 1, 1]])

In [40]:
numpy.hstack([m1, m2])

array([[1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0],
       [1, 1, 1, 1, 0, 0, 0, 0]])

In [41]:
[1, 2, 3] * [4, 5, 6]

TypeError: can't multiply sequence by non-int of type 'list'

In [45]:
x = numpy.array([1, 2, 3])
y = numpy.array([4, 5, 6])

In [46]:
z=  x * z
z

array([ 4, 20, 54])

In [47]:
x ** 2

array([1, 4, 9])

In [48]:
x.dot(y)

32

In [49]:
narr

array([[1, 2, 3],
       [0, 0, 0],
       [0, 0, 0]])

In [58]:
m = narr.T
m

array([[1, 0, 0],
       [2, 0, 0],
       [3, 0, 0]])

In [59]:
narr.astype('f')

array([[1., 2., 3.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [61]:
narr.sum()

6

In [62]:
narr.max()

3

In [63]:
narr.min()

0

In [64]:
narr.argmax()

2

In [65]:
narr.argmin()

3

In [66]:
narr.mean()

0.6666666666666666

In [68]:
narr.std()

1.0540925533894598

In [70]:
mr = numpy.arange(15) ** 2
mr

array([  0,   1,   4,   9,  16,  25,  36,  49,  64,  81, 100, 121, 144,
       169, 196])

In [71]:
mr[2]

4

In [72]:
mr[:5]

array([ 0,  1,  4,  9, 16])

In [73]:
mr[-2:]

array([169, 196])

In [74]:
mr[5:12:3]

array([ 25,  64, 121])

In [75]:
mr[-10::-2]

array([25,  9,  1])

In [76]:
mr[5:-1:-1]

array([], dtype=int32)

In [77]:
mr[5::-1]

array([25, 16,  9,  4,  1,  0])

In [ ]:
mr[7::-1]